//
//  Equipment.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Equipment: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _equipmentId: String?
    var _modifiedDate: NSNumber?
    var _description: String?
    var _displayName: String?
    var _verified: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "crowdedgym-mobilehub-558244246-equipment"
    }
    
    class func hashKeyAttribute() -> String {

        return "_equipmentId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_modifiedDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_equipmentId" : "equipmentId",
               "_modifiedDate" : "modifiedDate",
               "_description" : "description",
               "_displayName" : "displayName",
               "_verified" : "verified",
        ]
    }
}
