//
//  ExercisesCompleted.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class ExercisesCompleted: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _workoutHistoryId: String?
    var _userId: String?
    var _favorite: NSNumber?
    var _numCompleted: NSNumber?
    var _rating: NSNumber?
    var _workoutId: String?
    
    class func dynamoDBTableName() -> String {

        return "crowdedgym-mobilehub-558244246-exercisesCompleted"
    }
    
    class func hashKeyAttribute() -> String {

        return "_workoutHistoryId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_workoutHistoryId" : "workoutHistoryId",
               "_userId" : "userId",
               "_favorite" : "favorite",
               "_numCompleted" : "numCompleted",
               "_rating" : "rating",
               "_workoutId" : "workoutId",
        ]
    }
}
