//
//  UserProfiles.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class UserProfiles: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _joinedDate: NSNumber?
    var _avgWorkoutRatings: NSNumber?
    var _description: String?
    var _displayName: String?
    var _equipment: Set<String>?
    var _pictureUrl: String?
    
    class func dynamoDBTableName() -> String {

        return "crowdedgym-mobilehub-558244246-userProfiles"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_joinedDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_joinedDate" : "joinedDate",
               "_avgWorkoutRatings" : "avgWorkoutRatings",
               "_description" : "description",
               "_displayName" : "displayName",
               "_equipment" : "equipment",
               "_pictureUrl" : "pictureUrl",
        ]
    }
}
