//
//  Workouts.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Workouts: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _workoutId: String?
    var _modifiedDate: NSNumber?
    var _avgRating: NSNumber?
    var _description: String?
    var _displayName: String?
    var _duration: NSNumber?
    var _numRatings: NSNumber?
    var _recommendedEquipment: Set<String>?
    var _requiredEquipment: Set<String>?
    var _routines: [String: String]?
    var _trainingType: String?
    var _userSubmitted: String?
    
    class func dynamoDBTableName() -> String {

        return "crowdedgym-mobilehub-558244246-workouts"
    }
    
    class func hashKeyAttribute() -> String {

        return "_workoutId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_modifiedDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_workoutId" : "workoutId",
               "_modifiedDate" : "modifiedDate",
               "_avgRating" : "avgRating",
               "_description" : "description",
               "_displayName" : "displayName",
               "_duration" : "duration",
               "_numRatings" : "numRatings",
               "_recommendedEquipment" : "recommendedEquipment",
               "_requiredEquipment" : "requiredEquipment",
               "_routines" : "routines",
               "_trainingType" : "trainingType",
               "_userSubmitted" : "userSubmitted",
        ]
    }
}
